language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install twisted autobahn coveralls asgiref
script:
  - nosetests --with-coverage --cover-package=txasgiresource
after_success:
  - coveralls